### ISSUE TITLE
Dark theme for web version of myordbok [Feature Request]

### ISSUE THREAD

**Issue by nyinyinyanlin** [scriptive/myordbok#16]
I am a frequent user of MyOrdbok, particularly the web version of it. I love MyOrdbok! I believe implementing a light/dark UI will be beneficial for some users since the white background is eye tiring and too bright. Can you please kindly implement this feature? A simple toggle switch.

Thank you very much and love your work!

**Comment by khensolomon** [comment]
Hi @nyinyinyanlin thank you for reminding me, I will be sure to add theme mode on the next update, I think it is one of the most required feature nowadays.

**Comment by khensolomon** [comment]
Hi @nyinyinyanlin, I am happy to notify that light/dark UI have been implemented. This Feature Request would be closed soon.
